add_test( SQUiDTest.CountingQueryAnd /home/ubuntu/final_product/SQUiD/bin/main_test [==[--gtest_filter=SQUiDTest.CountingQueryAnd]==] --gtest_also_run_disabled_tests)
set_tests_properties( SQUiDTest.CountingQueryAnd PROPERTIES WORKING_DIRECTORY /home/ubuntu/final_product/SQUiD/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SQUiDTest.CountingQueryOr /home/ubuntu/final_product/SQUiD/bin/main_test [==[--gtest_filter=SQUiDTest.CountingQueryOr]==] --gtest_also_run_disabled_tests)
set_tests_properties( SQUiDTest.CountingQueryOr PROPERTIES WORKING_DIRECTORY /home/ubuntu/final_product/SQUiD/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SQUiDTest.PRSQuery /home/ubuntu/final_product/SQUiD/bin/main_test [==[--gtest_filter=SQUiDTest.PRSQuery]==] --gtest_also_run_disabled_tests)
set_tests_properties( SQUiDTest.PRSQuery PROPERTIES WORKING_DIRECTORY /home/ubuntu/final_product/SQUiD/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SQUiDTest.PublicKeySwitch /home/ubuntu/final_product/SQUiD/bin/main_test [==[--gtest_filter=SQUiDTest.PublicKeySwitch]==] --gtest_also_run_disabled_tests)
set_tests_properties( SQUiDTest.PublicKeySwitch PROPERTIES WORKING_DIRECTORY /home/ubuntu/final_product/SQUiD/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( main_test_TESTS SQUiDTest.CountingQueryAnd SQUiDTest.CountingQueryOr SQUiDTest.PRSQuery SQUiDTest.PublicKeySwitch)
